# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(758, 595)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.Send = QtWidgets.QPushButton(self.centralWidget)
        self.Send.setGeometry(QtCore.QRect(550, 190, 171, 51))
        self.Send.setObjectName("Send")
        self.Name = QtWidgets.QLabel(self.centralWidget)
        self.Name.setGeometry(QtCore.QRect(0, 6, 111, 41))
        self.Name.setObjectName("Name")
        self.DOB = QtWidgets.QLabel(self.centralWidget)
        self.DOB.setGeometry(QtCore.QRect(160, 6, 111, 41))
        self.DOB.setObjectName("DOB")
        self.Medicine = QtWidgets.QLabel(self.centralWidget)
        self.Medicine.setGeometry(QtCore.QRect(0, 106, 151, 41))
        self.Medicine.setObjectName("Medicine")
        self.NameTextBox = QtWidgets.QTextEdit(self.centralWidget)
        self.NameTextBox.setGeometry(QtCore.QRect(0, 50, 111, 31))
        self.NameTextBox.setObjectName("NameTextBox")
        self.DOBTextBOX = QtWidgets.QTextEdit(self.centralWidget)
        self.DOBTextBOX.setGeometry(QtCore.QRect(160, 50, 111, 31))
        self.DOBTextBOX.setObjectName("DOBTextBOX")
        self.InstructionBox = QtWidgets.QTextEdit(self.centralWidget)
        self.InstructionBox.setGeometry(QtCore.QRect(0, 230, 391, 201))
        self.InstructionBox.setObjectName("InstructionBox")
        self.Description = QtWidgets.QLabel(self.centralWidget)
        self.Description.setGeometry(QtCore.QRect(0, 196, 391, 31))
        self.Description.setObjectName("Description")
        self.Time = QtWidgets.QLabel(self.centralWidget)
        self.Time.setGeometry(QtCore.QRect(320, 106, 151, 41))
        self.Time.setObjectName("Time")
        self.DosageBox = QtWidgets.QTextEdit(self.centralWidget)
        self.DosageBox.setGeometry(QtCore.QRect(160, 150, 151, 31))
        self.DosageBox.setObjectName("DosageBox")
        self.Medicine_2 = QtWidgets.QLabel(self.centralWidget)
        self.Medicine_2.setGeometry(QtCore.QRect(160, 106, 141, 41))
        self.Medicine_2.setObjectName("Medicine_2")
        self.FrequencyBox = QtWidgets.QTextEdit(self.centralWidget)
        self.FrequencyBox.setGeometry(QtCore.QRect(320, 150, 151, 31))
        self.FrequencyBox.setObjectName("FrequencyBox")
        self.DOB_2 = QtWidgets.QLabel(self.centralWidget)
        self.DOB_2.setGeometry(QtCore.QRect(320, 6, 111, 41))
        self.DOB_2.setObjectName("DOB_2")
        self.PPSNBOX = QtWidgets.QTextEdit(self.centralWidget)
        self.PPSNBOX.setGeometry(QtCore.QRect(320, 50, 111, 31))
        self.PPSNBOX.setObjectName("PPSNBOX")
        self.qrcodeimage = QtWidgets.QLabel(self.centralWidget)
        self.qrcodeimage.setGeometry(QtCore.QRect(410, 260, 341, 271))
        self.qrcodeimage.setText("")
        self.qrcodeimage.setObjectName("qrcodeimage")
        self.Duration = QtWidgets.QLabel(self.centralWidget)
        self.Duration.setGeometry(QtCore.QRect(490, 106, 151, 41))
        self.Duration.setObjectName("Duration")
        self.DurationBox = QtWidgets.QTextEdit(self.centralWidget)
        self.DurationBox.setGeometry(QtCore.QRect(490, 150, 151, 31))
        self.DurationBox.setObjectName("DurationBox")
        self.MedicineTextBox = QtWidgets.QTextEdit(self.centralWidget)
        self.MedicineTextBox.setGeometry(QtCore.QRect(0, 150, 151, 31))
        self.MedicineTextBox.setObjectName("MedicineTextBox")
        self.Load = QtWidgets.QPushButton(self.centralWidget)
        self.Load.setGeometry(QtCore.QRect(200, 460, 171, 51))
        self.Load.setObjectName("Load")
        self.ButtonClear = QtWidgets.QPushButton(self.centralWidget)
        self.ButtonClear.setGeometry(QtCore.QRect(10, 460, 171, 51))
        self.ButtonClear.setObjectName("ButtonClear")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 758, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuCareTaker = QtWidgets.QMenu(self.menuBar)
        self.menuCareTaker.setObjectName("menuCareTaker")
        self.menuQR_Reader = QtWidgets.QMenu(self.menuBar)
        self.menuQR_Reader.setObjectName("menuQR_Reader")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.menuQR_Reader.addSeparator()
        self.menuBar.addAction(self.menuCareTaker.menuAction())
        self.menuBar.addAction(self.menuQR_Reader.menuAction())

        self.retranslateUi(MainWindow)
        self.Send.clicked.connect(self.InstructionBox.selectAll)
        self.Send.clicked['bool'].connect(self.DOBTextBOX.selectAll)
        self.Send.clicked['bool'].connect(self.NameTextBox.selectAll)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Send.setText(_translate("MainWindow", "Generate QR Code"))
        self.Name.setText(_translate("MainWindow", "Name"))
        self.DOB.setText(_translate("MainWindow", "DOB"))
        self.Medicine.setText(_translate("MainWindow", "Medication Name"))
        self.Description.setText(_translate("MainWindow", "Instruction"))
        self.Time.setText(_translate("MainWindow", "Frequency "))
        self.Medicine_2.setText(_translate("MainWindow", "Dosage"))
        self.DOB_2.setText(_translate("MainWindow", "PPSN"))
        self.Duration.setText(_translate("MainWindow", "Duration"))
        self.Load.setText(_translate("MainWindow", "Load into Array"))
        self.ButtonClear.setText(_translate("MainWindow", "Clear"))
        self.menuCareTaker.setTitle(_translate("MainWindow", "TakingCare"))
        self.menuQR_Reader.setTitle(_translate("MainWindow", "QR Reader"))

